export const ingredientCategories = [
  {
    id: "vegetables",
    name: "Vegetables",
    ingredients: [
      "Tomato",
      "Onion",
      "Garlic",
      "Bell Pepper",
      "Carrot",
      "Potato",
      "Spinach",
      "Broccoli",
      "Cucumber",
      "Zucchini",
      "Mushroom",
      "Lettuce",
      "Cabbage",
      "Corn",
      "Peas",
      "Green Beans",
      "Eggplant",
      "Cauliflower",
      "Sweet Potato",
      "Kale",
    ],
  },
  {
    id: "fruits",
    name: "Fruits",
    ingredients: [
      "Apple",
      "Banana",
      "Orange",
      "Lemon",
      "Lime",
      "Strawberry",
      "Blueberry",
      "Raspberry",
      "Blackberry",
      "Pineapple",
      "Mango",
      "Avocado",
      "Peach",
      "Pear",
      "Watermelon",
      "Grapes",
      "Kiwi",
      "Coconut",
      "Cherry",
      "Plum",
    ],
  },
  {
    id: "proteins",
    name: "Proteins",
    ingredients: [
      "Chicken",
      "Beef",
      "Pork",
      "Turkey",
      "Lamb",
      "Salmon",
      "Tuna",
      "Shrimp",
      "Tofu",
      "Eggs",
      "Chickpeas",
      "Lentils",
      "Black Beans",
      "Kidney Beans",
      "Tempeh",
      "Seitan",
      "Ground Beef",
      "Bacon",
      "Sausage",
      "Ham",
    ],
  },
  {
    id: "dairy",
    name: "Dairy",
    ingredients: [
      "Milk",
      "Butter",
      "Cheese",
      "Yogurt",
      "Cream",
      "Sour Cream",
      "Cream Cheese",
      "Cottage Cheese",
      "Mozzarella",
      "Cheddar",
      "Parmesan",
      "Feta",
      "Ricotta",
      "Gouda",
      "Blue Cheese",
      "Brie",
      "Goat Cheese",
      "Swiss Cheese",
      "Whipped Cream",
      "Buttermilk",
    ],
  },
  {
    id: "grains",
    name: "Grains",
    ingredients: [
      "Rice",
      "Pasta",
      "Bread",
      "Flour",
      "Oats",
      "Quinoa",
      "Couscous",
      "Barley",
      "Cornmeal",
      "Tortilla",
      "Bagel",
      "Pita",
      "Noodles",
      "Cereal",
      "Breadcrumbs",
      "Crackers",
      "Brown Rice",
      "Wild Rice",
      "Bulgur",
      "Farro",
    ],
  },
  {
    id: "spices",
    name: "Spices & Herbs",
    ingredients: [
      "Salt",
      "Pepper",
      "Basil",
      "Oregano",
      "Thyme",
      "Rosemary",
      "Cumin",
      "Paprika",
      "Cinnamon",
      "Nutmeg",
      "Chili Powder",
      "Curry Powder",
      "Ginger",
      "Turmeric",
      "Coriander",
      "Mint",
      "Parsley",
      "Cilantro",
      "Bay Leaf",
      "Sage",
    ],
  },
  {
    id: "condiments",
    name: "Condiments",
    ingredients: [
      "Olive Oil",
      "Vegetable Oil",
      "Vinegar",
      "Soy Sauce",
      "Hot Sauce",
      "Ketchup",
      "Mustard",
      "Mayonnaise",
      "Honey",
      "Maple Syrup",
      "Sugar",
      "Brown Sugar",
      "Tomato Sauce",
      "Tomato Paste",
      "Worcestershire Sauce",
      "BBQ Sauce",
      "Salsa",
      "Pesto",
      "Jam",
      "Peanut Butter",
    ],
  },
]

export const cuisineOptions = [
  { id: "italian", label: "Italian" },
  { id: "mexican", label: "Mexican" },
  { id: "chinese", label: "Chinese" },
  { id: "indian", label: "Indian" },
  { id: "japanese", label: "Japanese" },
  { id: "thai", label: "Thai" },
  { id: "french", label: "French" },
  { id: "mediterranean", label: "Mediterranean" },
  { id: "american", label: "American" },
  { id: "greek", label: "Greek" },
  { id: "spanish", label: "Spanish" },
  { id: "korean", label: "Korean" },
  { id: "vietnamese", label: "Vietnamese" },
  { id: "middle-eastern", label: "Middle Eastern" },
]

